# Generated by Django 6.0.7 on 2026-09-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='videos/processed/')),
                ('total_frames', models.IntegerField(default=0)),
                ('detected_frames', models.IntegerField(default=0)),
                ('detection_percentage', models.FloatField(default=0.0)),
                ('detected_shot', models.CharField(blank=True, default='', max_length=100)),
                ('shot_confidence', models.FloatField(default=0.0)),
                ('overall_score', models.IntegerField(default=0)),
                ('posture_score', models.IntegerField(default=0)),
                ('balance_score', models.IntegerField(default=0)),
                ('lower_body_score', models.IntegerField(default=0)),
                ('upper_body_score', models.IntegerField(default=0)),
                ('follow_through_score', models.IntegerField(default=0)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('coaching_feedback', models.JSONField(blank=True, default=list)),
                ('key_observations', models.JSONField(blank=True, default=list)),
                ('shot_reasoning', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis.uploadedvideo')),
            ],
        ),
    ]
